apiVersion: v1
kind: Service
metadata:
  name: {{ include "redis-cluster.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
spec:
  clusterIP: None
  selector:
    {{- include "redis-cluster.selectorLabels" . | nindent 4 }}
