apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.setup.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "redis-cluster.labels" . | nindent 4 }}
  {{- with .Values.setup.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.setup.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
rules:
- apiGroups: ["apps"]
  resources: ["statefulsets"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "watch", "list"]
- apiGroups: [""]
  resources: ["pods/exec"]
  verbs: ["create", "get"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Values.setup.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
subjects:
- kind: ServiceAccount
  name: {{ .Values.setup.serviceAccount.name }}
roleRef:
  kind: Role
  name: {{ .Values.setup.serviceAccount.name }}
  apiGroup: rbac.authorization.k8s.io
