name: CI

permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  build:
    name: Run
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up chart-testing
        uses: helm/chart-testing-action@e6669bcd63d7cb57cb4380c33043eebe5d111992
      - name: Set up Helm
        uses: azure/setup-helm@b7246b12e77f7134dc2d460a3d5bad15bbe29390
        with:
          version: v3.11.2
      # - uses: actions/setup-python@v5
      #   with:
      #     python-version: '3.9'
      #     check-latest: true

      # - name: Run chart-testing (list-changed)
      #   id: list-changed
      #   run: |
      #     changed=$(ct list-changed --target-branch ${{ github.event.repository.default_branch }})
      #     if [[ -n "$changed" ]]; then
      #       echo "changed=true" >> "$GITHUB_OUTPUT"
      #     fi

      - name: Run helm lint
        uses: WyriHaximus/github-action-helm3@v4
        # if: steps.list-changed.outputs.changed == 'true'
        with:
          exec: helm lint --strict redis-cluster

      - name: Run chart-testing (lint)
        # if: steps.list-changed.outputs.changed == 'true'
        run: ct lint --charts redis-cluster --target-branch ${{ github.event.repository.default_branch }}

      - name: Create kind cluster
        # if: steps.list-changed.outputs.changed == 'true'
        uses: helm/kind-action@v1.11.0

      - name: Run chart-testing (install)
        # if: steps.list-changed.outputs.changed == 'true'
        run: ct install --charts redis-cluster --target-branch ${{ github.event.repository.default_branch }}
